services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: notify
      POSTGRES_PASSWORD: notify_pass
      POSTGRES_DB: go_notify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grpc-server:
    build:
      context: ../
      dockerfile: deployments/docker/Dockerfile.grpc
    container_name: go-notify-grpc
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq
      - postgres

  worker:
    build:
      context: ../
      dockerfile: deployments/docker/Dockerfile.worker
    container_name: go-notify-worker
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data:
