services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: notify
      POSTGRES_PASSWORD: notify_pass
      POSTGRES_DB: go_notify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grpc-server:
    build:
      context: ../
      dockerfile: deployments/docker/Dockerfile.grpc
    container_name: go-notify-grpc
    environment:
      - GRPC_PORT=:50051
      - METRICS_PORT=:9091
      - RABBITMQ_QUEUE=notifications
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_DSN=postgres://notify:notify_pass@postgres:5432/go_notify?sslmode=disable
    ports:
      - "50051:50051"
      - "9091:9090"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  worker:
    build:
      context: ../
      dockerfile: deployments/docker/Dockerfile.worker
    container_name: go-notify-worker
    environment:
      - NTFY_TOPIC=go-notify-sid
      - RABBITMQ_QUEUE=notifications
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_DSN=postgres://notify:notify_pass@postgres:5432/go_notify?sslmode=disable
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    user: "10001:10001"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki-data

volumes:
  postgres_data:
  loki-data:
