auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    dir: /loki-data/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki-data/index
    cache_location: /loki-data/tsdb-cache
  boltdb_shipper:
    active_index_directory: /loki-data/index
    cache_location: /loki-data/boltdb-cache
  filesystem:
    directory: /loki-data/chunks

compactor:
  working_directory: /loki-data/compactor

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
